source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MarkedView_Example', :exclusive => true do
  pod 'MarkedView', :path => '../'
end

target 'MarkedView_Tests', :exclusive => true do
  pod 'MarkedView', :path => '../'

  
end
