source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MarkedView_Example' do
  pod 'MarkedView', :path => '../'
end

target 'MarkedView_Tests' do
  pod 'MarkedView', :path => '../'

  
end
